# Generated by Django 3.2.7 on 2021-09-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='tagNome',
        ),
    ]
