# Generated by Django 3.2.7 on 2021-09-19 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_tag_tag_tagnome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagNome',
            new_name='tagName',
        ),
    ]
