# Generated by Django 3.2.7 on 2021-09-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_tagnome_tag_tagname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagName',
            new_name='tag',
        ),
    ]
